sudo: required

language: generic

env:
  IMAGE_VHOST_PROXY: docksal/vhost-proxy:dev
  DOCKSAL_VHOST_PROXY_ACCESS_LOG: 1
  DOCKSAL_VHOST_PROXY_DEBUG_LOG: 1
  DOCKSAL_VHOST_PROXY_STATS_LOG: 1
  # Only use seconds here, so that these can be used with "sleep" as well
  PROJECT_INACTIVITY_TIMEOUT: 30s
  PROJECT_DANGLING_TIMEOUT: 60s
  PROJECTS_ROOT: ${TRAVIS_BUILD_DIR}/projects
  DOCKSAL_VERSION: feature/docksal-projects-volume

services:
  - docker

install:
  - sudo sudo curl -L https://raw.githubusercontent.com/docksal/docksal/${DOCKSAL_VERSION}/bin/fin -o /usr/local/bin/fin && sudo chmod +x /usr/local/bin/fin
  - fin version
  - fin update
  - fin sysinfo

before_script:
  - .travis/before_script.sh
  - ls -la "$PROJECTS_ROOT"

script:
  - make
  - make start
  - make CMD="env" exec  # Views env variables picked up by proxy
  - make CMD="ls -la /projects" exec  # View the contents of the /projects folder
  - make test

after_failure:
  - make logs
