sudo: required

language: generic

env:
  OS: linux
  IMAGE_VHOST_PROXY: vhost-proxy:test
  # Only use seconds here, so that these can be used with "sleep" as well
  PROXY_INACTIVITY_TIMEOUT: 30s
  PROXY_DANGLING_TIMEOUT: 60s
  PROXY_DEBUG: 1

services:
  - docker

install:
  - sudo sudo curl -L https://raw.githubusercontent.com/docksal/docksal/develop/bin/fin -o /usr/local/bin/fin && sudo chmod +x /usr/local/bin/fin
  - fin version
  - fin update
  - fin docker build -t ${IMAGE_VHOST_PROXY} .
  - IMAGE_VHOST_PROXY=${IMAGE_VHOST_PROXY} INACTIVITY_TIMEOUT=${PROXY_INACTIVITY_TIMEOUT} DANGLING_TIMEOUT=${PROXY_DANGLING_TIMEOUT} fin reset proxy
  - fin sysinfo

before_script:
  - git clone https://github.com/docksal/drupal7.git ../drupal7 && cd ../drupal7 && fin init && fin stop

script:
  - bats $(ls -1 --hide=drupal7 ../*/tests/smoke-test.bats)
