sudo: required

language: generic

env:
  IMAGE_VHOST_PROXY: docksal/vhost-proxy:dev
  # Only use seconds here, so that these can be used with "sleep" as well
  PROJECT_INACTIVITY_TIMEOUT: 30s
  PROJECT_DANGLING_TIMEOUT: 60s
  DOCKSAL_VERSION: develop

services:
  - docker

install:
  - sudo sudo curl -L https://raw.githubusercontent.com/docksal/docksal/${DOCKSAL_VERSION}/bin/fin -o /usr/local/bin/fin && sudo chmod +x /usr/local/bin/fin
  - fin version
  - fin update
  - fin sysinfo

before_script:
  - make
  - PROJECTS_ROOT=$TRAVIS_BUILD_DIR fin system reset vhost-proxy
  - .travis/before_script.sh

script:
  - make test
